name: 'Run virus scan'
description: 'Runs virus scan on artifacts of published releases, including source and binary packages'
inputs:
  owner:
    description: 'Owner of the repository containing the release to virus scan'
    required: true
  repo:
    description: 'Name of the repository containing the release to virus scan'
    required: true
  tag:
    description: 'The tag of the release to virus scan'
    required: true
  github-access-token:
    description: 'A GitHub access token that can read and write the release details'
    required: true
  slack-token:
    description: 'A Slack bearer token for posting virus warnings to a Slack channel'
    required: false
  slack-channel:
    description: 'The Slack channel to post virus warnings to'
    required: false
runs:
  using: "composite"
  steps:
    - id: install
      name: Install ClamAV
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install clamav
        clamVersion=$(clamscan --version)
        echo $clamVersion
        echo "CLAMAV_VERSION=$clamVersion" >> $GITHUB_ENV
    - id: update
      name: Update virus signature database
      shell: bash
      run: |
        sudo systemctl stop clamav-freshclam
        sudo freshclam
        sudo systemctl start clamav-freshclam
    - name: Get release
      uses: actions/github-script@v4.1.0
      with:
        github-token: ${{ inputs.github-access-token }}
        script: |
          const fs = require('fs');
          
          await io.mkdirP('github-release-assets');
          
          let release = await github.repos.getReleaseByTag({
            owner: '${{ inputs.owner }}',
            repo: '${{ inputs.repo }}',
            tag: '${{ inputs.tag }}'
          });
          
          core.exportVariable('RELEASE_ID', release.data.id);
          core.exportVariable('RELEASE_BODY', release.data.body);
          core.exportVariable('RELEASE_HTML_URL', release.data.html_url);
          
          for (const assetInfo of release.data.assets) {
            let asset = await github.request(assetInfo.browser_download_url);
            await fs.writeFile('github-release-assets/' + assetInfo.name, Buffer.from(asset.data), () => {});
          }
          
          let zipball = await github.request(release.data.zipball_url);
          await fs.writeFile('github-release-assets/source.zip', Buffer.from(zipball.data), () => {});
          
          let tarball = await github.request(release.data.tarball_url);
          await fs.writeFile('github-release-assets/source.tar.gz', Buffer.from(tarball.data), () => {});
          
    - name: Run ClamAV
      # Don't automatically fail on first non-zero return code by skipping -e parameter
      # May highlight as error but docs say is valid: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
      shell: "/usr/bin/bash {0}"
      run: |
        sudo clamscan --infected github-release-assets/ > scan-results.log
        echo "CLAMAV_RETURN_CODE=$?" >> $GITHUB_ENV
        exit 0;
    - name: Notify Slack on viruses detected
      shell: pwsh
      env:
        SLACK_TOKEN: ${{ inputs.slack-token }}
        SLACK_CHANNEL: ${{ inputs.slack-channel }}
      run: |
        if ($Env:SLACK_TOKEN -eq '') {
          Write-Output "inputs.slack-token not provided, can't post to Slack"
          exit 0
        }
        if ($Env:SLACK_TOKEN -eq '') {
          Write-Output "inputs.slack-channel not provided, can't post to Slack"
          exit 0
        }
        if ($Env:CLAMAV_RETURN_CODE -eq '0') {
          Write-Output "No virus detected, no reason to alert"
          exit 0
        }

        $token = $Env:SLACK_TOKEN
        $url = $Env:RELEASE_HTML_URL
        $headers = @{
            'Authorization' = "Bearer $token"
        }
        $body = @{
          channel = $Env:SLACK_CHANNEL
          text = "ClamAV has detected a virus in the release at $url"
          username = 'Virus Scan Workflow'
          icon_emoji = 'biohazard_sign'
          unfurl_links = false
          unfurl_media = false
        } | ConvertTo-Json

        $result = Invoke-RestMethod -Method POST -Uri https://slack.com/api/chat.postMessage -ContentType "application/json; charset=utf-8" -Headers $headers -Body $body

        exit $(If ($result.ok -eq True) { 0 } Else { 1 })
    - name: Update release notes
      uses: actions/github-script@v4.1.0
      with:
        github-token: ${{ inputs.github-access-token }}
        script: |
          const { CLAMAV_VERSION, CLAMAV_RETURN_CODE, RELEASE_ID, RELEASE_BODY } = process.env;
          const fs = require('fs');
          let status = 'No viruses detected';
          if (CLAMAV_RETURN_CODE === '1') {
            status = 'Virus(es) detected';
          } else if (CLAMAV_RETURN_CODE === '2') {
            status = 'Scanning error occurred';
          }
          fs.readFile('scan-results.log', { encoding: 'utf8' }, (err, fileText) => {
          
            console.log(fileText);
            let releaseBody = RELEASE_BODY + '\n\n<details><summary><b>🛡 ClamAV virus scan results: ' + 
              status + '</b></summary>\n\n```\nVersion: ' + CLAMAV_VERSION + 
              '\nScan Date: ' + new Date().toUTCString() + '\n' + fileText + '\n```\n\n</details>';
            github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: RELEASE_ID,
              body: releaseBody
            });
          });
