name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: No viruses
            release-id: 49940655
            tag: test/no-virus
            expected-result: 0
          - name: Virus test file
            release-id: 49943009
            tag: test/virus-test-file
            expected-result: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Reset test release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let releaseId = ${{ matrix.release-id }};

            github.rest.repos.updateRelease({
              owner: 'Particular',
              repo: 'virus-scan-action',
              release_id: releaseId,
              body: 'This is the normal release text, before adding the virus scan results.'
            });
      - name: Run
        uses: ./
        with:
          owner: Particular
          repo: virus-scan-action
          tag: ${{ matrix.tag }}
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: automation-testing
      - name: Check result
        shell: pwsh
        run: |
          $code = $Env:CLAMAV_RETURN_CODE
          Write-Host "ClamAV Return Code: $code"
          if ($code -ne '${{ matrix.expected-result }}') { throw "ClamAV did not return expected result of ${{ matrix.expected-result }}"}
